# data file type definitions
DATA_TYPE_POSITIONING = 0
DATA_TYPE_MOTION_DATA = 1
DATA_TYPE_POSITIONING_AND_MOTION_DATA = 2
DATA_TYPE_MULTIDEVICE_POSITIONING = 3
DATA_TYPE_MULTIDEVICE_POSITIONING_AND_MOTION_DATA = 4
