# data collection type definitions
DATA_TYPE_POSITIONING = 0
DATA_TYPE_RANGING = 1
DATA_TYPE_MOTION_DATA = 2

# osc message indices relative to tag
OSC_TIME_INDEX_ABSOLUTE = 1
OSC_1D_RANGE_INDEX = 1
OSC_1D_VELOCITY_INDEX = 2
OSC_3D_POS_X_INDEX = 3
OSC_3D_POS_Y_INDEX = 4
OSC_3D_POS_Z_INDEX = 5
OSC_3D_VEL_X_INDEX = 6
OSC_3D_VEL_Y_INDEX = 7
OSC_3D_VEL_Z_INDEX = 8
OSC_PRESSURE_INDEX = 9
OSC_ACC_X_INDEX = 10
OSC_ACC_Y_INDEX = 11
OSC_ACC_Z_INDEX = 12
OSC_MAG_X_INDEX = 13
OSC_MAG_Y_INDEX = 14
OSC_MAG_Z_INDEX = 15
OSC_ANG_VEL_X_INDEX = 16
OSC_ANG_VEL_Y_INDEX = 17
OSC_ANG_VEL_Z_INDEX = 18
OSC_EULER_HEADING_INDEX = 19
OSC_EULER_ROLL_INDEX = 20
OSC_EULER_PITCH_INDEX = 21
OSC_QUATERNION_W_INDEX = 22
OSC_QUATERNION_X_INDEX = 23
OSC_QUATERNION_Y_INDEX = 24
OSC_QUATERNION_Z_INDEX = 25
OSC_LIN_ACC_X_INDEX = 26
OSC_LIN_ACC_Y_INDEX = 27
OSC_LIN_ACC_Z_INDEX = 28
OSC_GRAVITY_X_INDEX = 29
OSC_GRAVITY_Y_INDEX = 30
OSC_GRAVITY_Z_INDEX = 31

OSC_INDEX_DICT = {
    "time": OSC_TIME_INDEX_ABSOLUTE,
    "1D_range": OSC_1D_RANGE_INDEX,
    "1D_velocity": OSC_1D_VELOCITY_INDEX,
    "3D_position_X": OSC_3D_POS_X_INDEX,
    "3D_position_Y": OSC_3D_POS_Y_INDEX,
    "3D_position_Z": OSC_3D_POS_Z_INDEX,
    "3D_velocity_X": OSC_3D_VEL_X_INDEX,
    "3D_velocity_Y": OSC_3D_VEL_Y_INDEX,
    "3D_velocity_Z": OSC_3D_VEL_Z_INDEX,
    "pressure": OSC_PRESSURE_INDEX,
    "acceleration_x": OSC_ACC_X_INDEX,
    "acceleration_y": OSC_ACC_Y_INDEX,
    "acceleration_z": OSC_ACC_Z_INDEX,
    "magnetic_x": OSC_MAG_X_INDEX,
    "magnetic_y": OSC_MAG_Y_INDEX,
    "magnetic_z": OSC_MAG_Z_INDEX,
    "angular_vel_x": OSC_ANG_VEL_X_INDEX,
    "angular_vel_y": OSC_ANG_VEL_Y_INDEX,
    "angular_vel_z": OSC_ANG_VEL_Z_INDEX,
    "euler_heading": OSC_EULER_HEADING_INDEX,
    "euler_roll": OSC_EULER_ROLL_INDEX,
    "euler_pitch": OSC_EULER_PITCH_INDEX,
    "quaternion_w": OSC_QUATERNION_W_INDEX,
    "quaternion_x": OSC_QUATERNION_X_INDEX,
    "quaternion_y": OSC_QUATERNION_Y_INDEX,
    "quaternion_z": OSC_QUATERNION_Z_INDEX,
    "lin_acc_x": OSC_LIN_ACC_X_INDEX,
    "lin_acc_y": OSC_LIN_ACC_Y_INDEX,
    "lin_acc_z": OSC_LIN_ACC_Z_INDEX,
    "gravity_x": OSC_GRAVITY_X_INDEX,
    "gravity_y": OSC_GRAVITY_Y_INDEX,
    "gravity_z": OSC_GRAVITY_Z_INDEX
}
